version: '2'

services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: testpw
      MYSQL_DATABASE: test
   
  application:
    image: maven
    links:
      - database:mysql
    working_dir: /application
    volumes:
      - ./:/application
      - ~/.m2:/root/.m2
    ports:
      - 8080
    command: sh -c 'sleep 10 && mvn spring-boot:run'